on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Check flake
        run: cd nixos-config && nix flake check
      - name: Show flake info
        run: cd nixos-config && nix flake show
