# name: Publish every Git push to main to FlakeHub
# on:
#   push:
#     branches:
#       - main

# jobs:
#   flakehub-publish:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     defaults:
#       run:
#         working-directory: ./nixos-config
#     steps:
#       - uses: actions/checkout@v4

#       - uses: DeterminateSystems/nix-installer-action@main

#       - uses: DeterminateSystems/flakehub-push@main
#         with:
#           rolling: true
#           visibility: private
#           include-output-paths: true
